# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# Pierfrancesco Passerini <p.passerini@gmail.com>, 2019
# Pietro F. Fontana, 2020
# Saverio <saverio.brancaccio@gmail.com>, 2020
# Giuseppe Pignataro (Fastbyte01) <rogepix@gmail.com>, 2021
# Vincenzo Reale <vinx.reale@gmail.com>, 2022
# vincenzo sammarco, 2022
# Paolo Zamponi <feus73@gmail.com>, 2023
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-11-29 13:55+0100\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: Paolo Zamponi <feus73@gmail.com>, 2023\n"
"Language-Team: Italian (Italy) (https://app.transifex.com/calamares/teams/20061/it_IT/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: it_IT\n"
"Plural-Forms: nplurals=3; plural=n == 1 ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;\n"

#: src/modules/bootloader/main.py:46
msgid "Install bootloader."
msgstr "Installa il bootloader."

#: src/modules/bootloader/main.py:671
msgid "Failed to install grub, no partitions defined in global storage"
msgstr ""
"Installazione di grub non riuscita, nessuna partizione definita "
"nell'archiviazione globale"

#: src/modules/bootloader/main.py:931
msgid "Bootloader installation error"
msgstr "Errore di installazione del boot loader"

#: src/modules/bootloader/main.py:932
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Impossibile installare il bootloader. Il comando di installazione "
"<pre>{!s}</pre> ha restituito il codice di errore {!s}."

#: src/modules/displaymanager/main.py:525
msgid "Cannot write LXDM configuration file"
msgstr "Impossibile scrivere il file di configurazione di LXDM"

#: src/modules/displaymanager/main.py:526
msgid "LXDM config file {!s} does not exist"
msgstr "Il file di configurazione di LXDM {!s} non esiste"

#: src/modules/displaymanager/main.py:614
msgid "Cannot write LightDM configuration file"
msgstr "Impossibile scrivere il file di configurazione di LightDM"

#: src/modules/displaymanager/main.py:615
msgid "LightDM config file {!s} does not exist"
msgstr "Il file di configurazione di LightDM {!s} non esiste"

#: src/modules/displaymanager/main.py:700
msgid "Cannot configure LightDM"
msgstr "Impossibile configurare LightDM"

#: src/modules/displaymanager/main.py:701
msgid "No LightDM greeter installed."
msgstr "Nessun LightDM greeter installato."

#: src/modules/displaymanager/main.py:732
msgid "Cannot write SLIM configuration file"
msgstr "Impossibile scrivere il file di configurazione di SLIM"

#: src/modules/displaymanager/main.py:733
msgid "SLIM config file {!s} does not exist"
msgstr "Il file di configurazione di SLIM {!s} non esiste"

#: src/modules/displaymanager/main.py:956
msgid "No display managers selected for the displaymanager module."
msgstr ""
"Non è stato selezionato alcun display manager per il modulo displaymanager"

#: src/modules/displaymanager/main.py:957
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr ""
"La lista dei display manager è vuota o non definita sia in globalstorage che"
" in displaymanager.conf."

#: src/modules/displaymanager/main.py:1044
msgid "Display manager configuration was incomplete"
msgstr "La configurazione del display manager è incompleta"

#: src/modules/dracut/main.py:29
msgid "Creating initramfs with dracut."
msgstr "Creazione di initramfs con dracut."

#: src/modules/dracut/main.py:63
msgid "Failed to run dracut"
msgstr "Impossibile eseguire dracut"

#: src/modules/dracut/main.py:64
#, python-brace-format
msgid "Dracut failed to run on the target with return code: {return_code}"
msgstr ""
"Esecuzione di dracut nella destinazione non riuscita con codice restituito: "
"{return_code}"

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "Job python fittizio."

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:104
#: src/modules/dummypython/main.py:105
msgid "Dummy python step {}"
msgstr "Python step {} fittizio"

#: src/modules/fstab/main.py:29
msgid "Writing fstab."
msgstr "Scrittura di fstab."

#: src/modules/fstab/main.py:382 src/modules/fstab/main.py:388
#: src/modules/fstab/main.py:416 src/modules/initcpiocfg/main.py:267
#: src/modules/initcpiocfg/main.py:271 src/modules/initramfscfg/main.py:85
#: src/modules/initramfscfg/main.py:89 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:344 src/modules/networkcfg/main.py:106
#: src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/rawfs/main.py:165
msgid "Configuration Error"
msgstr "Errore di Configurazione"

#: src/modules/fstab/main.py:383 src/modules/initramfscfg/main.py:86
#: src/modules/mount/main.py:345 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/rawfs/main.py:166
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "Nessuna partizione definita per l'uso con <pre>{!s}</pre>."

#: src/modules/fstab/main.py:389 src/modules/initramfscfg/main.py:90
#: src/modules/localecfg/main.py:141 src/modules/networkcfg/main.py:107
#: src/modules/openrcdmcryptcfg/main.py:77
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr "Nessun punto di mount root è dato in l'uso per <pre>{!s}</pre>"

#: src/modules/fstab/main.py:417
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr ""
"Non viene fornita alcuna configurazione <pre>{!s}</pre> per <pre>{!s}</pre> "
"da utilizzare."

#: src/modules/grubcfg/main.py:30
msgid "Configure GRUB."
msgstr "Configura GRUB."

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "Impostazione del clock hardware."

#: src/modules/initcpiocfg/main.py:27
msgid "Configuring mkinitcpio."
msgstr "Configurazione di mkinitcpio."

#: src/modules/initcpiocfg/main.py:268
msgid "No partitions are defined for <pre>initcpiocfg</pre>."
msgstr "Nessuna partizione definita per <pre>initcpiocfg</pre>."

#: src/modules/initcpiocfg/main.py:272
msgid "No root mount point for <pre>initcpiocfg</pre>."
msgstr ""

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "Configurazione di initramfs."

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "Configurazione della localizzazione."

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr "Creazione di initramfs con mkinitfs."

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr "Impossibile eseguire mkinitfs sulla destinazione"

#: src/modules/mkinitfs/main.py:50
msgid "The exit code was {}"
msgstr "Il codice di uscita era {}"

#: src/modules/mount/main.py:43
msgid "Mounting partitions."
msgstr "Montaggio partizioni."

#: src/modules/mount/main.py:171 src/modules/mount/main.py:207
msgid "Internal error mounting zfs datasets"
msgstr "Errore interno durante il montaggio dei dataset zfs"

#: src/modules/mount/main.py:183
msgid "Failed to import zpool"
msgstr "Importazione zpool non riuscita"

#: src/modules/mount/main.py:199
msgid "Failed to unlock zpool"
msgstr "Sblocco zpool non riuscito"

#: src/modules/mount/main.py:216 src/modules/mount/main.py:221
msgid "Failed to set zfs mountpoint"
msgstr "Impossibile impostare il punto di montaggio zfs"

#: src/modules/mount/main.py:386
msgid "zfs mounting error"
msgstr "errore di montaggio di zfs"

#: src/modules/networkcfg/main.py:30
msgid "Saving network configuration."
msgstr "Salvataggio della configurazione di rete."

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "Configurazione del servizio OpenRC dmcrypt."

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "Installa pacchetti."

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "Elaborazione dei pacchetti (%(count)d / %(total)d)"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "Installando un pacchetto."
msgstr[1] "Installazione di %(num)d pacchetti."
msgstr[2] "Installazione di %(num)d pacchetti."

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "Rimuovendo un pacchetto."
msgstr[1] "Rimozione di %(num)d pacchetti."
msgstr[2] "Rimozione di %(num)d pacchetti."

#: src/modules/packages/main.py:775 src/modules/packages/main.py:787
#: src/modules/packages/main.py:815
msgid "Package Manager error"
msgstr "Errore del gestore dei pacchetti"

#: src/modules/packages/main.py:776
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr ""
"Il gestore pacchetti non ha potuto preparare gli aggiornamenti. Il comando "
"<pre>{!s}</pre> ha restituito il codice di errore {!s}."

#: src/modules/packages/main.py:788
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr ""
"Il gestore pacchetti non ha potuto aggiornare il sistema. Il "
"comando<pre>{!s}</pre> ha restituito il codice di errore {!s}."

#: src/modules/packages/main.py:816
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Il gestore pacchetti non ha potuto apportare modifiche al sistema "
"installato. Il comando <pre>{!s}</pre> ha restituito il codice di errore "
"{!s}."

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "Configura il tema Plymouth"

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "Installazione dei dati."

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "Configura i servizi OpenRC"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr "Impossibile aggiungere il servizio {name!s} al run-level {level!s}."

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr "Impossibile rimuovere il servizio {name!s} dal run-level {level!s}."

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""
"Service-action sconosciuta <code>{arg!s}</code> per il servizio {name!s} nel"
" run-level {level!s}."

#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "Impossibile modificare il servizio"

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
"La chiamata <code>rc-update {arg!s}</code> in chroot ha ritornato il codice "
"di errore {num!s}."

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "Il runlevel di destinazione non esiste"

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"Il percorso del runlevel {level!s} è <code>{path!s}</code>, ma non esiste."

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "Il servizio target non esiste"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"Il percorso del servizio {name!s} è <code>{path!s}</code>, ma non esiste."

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd units"
msgstr ""

#: src/modules/services-systemd/main.py:64
msgid "Cannot modify unit"
msgstr "Impossibile modificare l'unità"

#: src/modules/services-systemd/main.py:65
msgid ""
"<code>systemctl {_action!s}</code> call in chroot returned error code "
"{_exit_code!s}."
msgstr ""
"La chiamata <code>systemctl {_action!s}</code> in chroot ha restituito il "
"codice di errore {_exit_code!s}."

#: src/modules/services-systemd/main.py:66
msgid "Cannot {_action!s} systemd unit <code>{_name!s}</code>."
msgstr ""

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "Copia dei file system."

#: src/modules/unpackfs/main.py:255
msgid "rsync failed with error code {}."
msgstr "rsync non riuscito con codice d'errore {}."

#: src/modules/unpackfs/main.py:300
msgid "Unpacking image {}/{}, file {}/{}"
msgstr "Estrazione immagine {}/{}, file {}/{}"

#: src/modules/unpackfs/main.py:315
msgid "Starting to unpack {}"
msgstr "Avvio dell'estrazione {}"

#: src/modules/unpackfs/main.py:324 src/modules/unpackfs/main.py:480
msgid "Failed to unpack image \"{}\""
msgstr "Estrazione dell'immagine \"{}\" non riuscita"

#: src/modules/unpackfs/main.py:443
msgid "No mount point for root partition"
msgstr "Nessun punto di montaggio per la partizione di root"

#: src/modules/unpackfs/main.py:444
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr "l'archiviazione globale non contiene una chiave \"rootMountPoint\"."

#: src/modules/unpackfs/main.py:447
msgid "Bad mount point for root partition"
msgstr "Punto di montaggio per la partizione di root errato"

#: src/modules/unpackfs/main.py:448
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr "rootMountPoint è \"{}\",  non esiste."

#: src/modules/unpackfs/main.py:452 src/modules/unpackfs/main.py:468
#: src/modules/unpackfs/main.py:472 src/modules/unpackfs/main.py:478
#: src/modules/unpackfs/main.py:515
msgid "Bad unpackfs configuration"
msgstr "Configurazione unpackfs errata"

#: src/modules/unpackfs/main.py:453
msgid "There is no configuration information."
msgstr "Non ci sono informazioni di configurazione."

#: src/modules/unpackfs/main.py:469
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr "Il filesystem per \"{}\" ({}) non è supportato dal kernel corrente"

#: src/modules/unpackfs/main.py:473
msgid "The source filesystem \"{}\" does not exist"
msgstr "Il filesystem sorgente \"{}\" non esiste"

#: src/modules/unpackfs/main.py:479
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr ""
"Impossibile trovare unsquashfs, assicurati di avere installato il pacchetto "
"squashfs-tools."

#: src/modules/unpackfs/main.py:516
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "La destinazione del sistema \"{}\" non è una directory"

#: src/modules/zfshostid/main.py:27
msgid "Copying zfs generated hostid."
msgstr ""
