# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# F V, 2024
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-11-29 13:55+0100\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: F V, 2024\n"
"Language-Team: Interlingua (https://app.transifex.com/calamares/teams/20061/ia/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: ia\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: src/modules/bootloader/main.py:46
msgid "Install bootloader."
msgstr "Installar cargator de initio."

#: src/modules/bootloader/main.py:671
msgid "Failed to install grub, no partitions defined in global storage"
msgstr ""
"Falleva a installar le grub, necun partitiones definite in le immagazinage "
"global."

#: src/modules/bootloader/main.py:931
msgid "Bootloader installation error"
msgstr "Error de installation del cargator de initio"

#: src/modules/bootloader/main.py:932
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Le cargator de initio non poteva esser installate. Le commando de "
"installation <pre>{!s}</pre> retornava le codice de error {!s}."

#: src/modules/displaymanager/main.py:525
msgid "Cannot write LXDM configuration file"
msgstr "Non pote scriber le file de configuration LXDM"

#: src/modules/displaymanager/main.py:526
msgid "LXDM config file {!s} does not exist"
msgstr "Le file de configuration de LXDM {!s} non existe"

#: src/modules/displaymanager/main.py:614
msgid "Cannot write LightDM configuration file"
msgstr "Non pote scriber le file de configuration LightDM"

#: src/modules/displaymanager/main.py:615
msgid "LightDM config file {!s} does not exist"
msgstr "Le file de configuration de LightDM {!s} non existe"

#: src/modules/displaymanager/main.py:700
msgid "Cannot configure LightDM"
msgstr "Non pote configurar LightDM"

#: src/modules/displaymanager/main.py:701
msgid "No LightDM greeter installed."
msgstr "Necun systema de benvenita de LightDM installate."

#: src/modules/displaymanager/main.py:732
msgid "Cannot write SLIM configuration file"
msgstr "Non pote scriber le file de configuration de SLIM"

#: src/modules/displaymanager/main.py:733
msgid "SLIM config file {!s} does not exist"
msgstr "Le file de configuration de SLIM {!s} non existe"

#: src/modules/displaymanager/main.py:956
msgid "No display managers selected for the displaymanager module."
msgstr ""
"Necun gestor de visualisation selectionate pro le modulo de displaymanager."

#: src/modules/displaymanager/main.py:957
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr ""
"Le lista de displaymanagers es vacue o non definite in globalstorage e in "
"displaymanager.conf."

#: src/modules/displaymanager/main.py:1044
msgid "Display manager configuration was incomplete"
msgstr "Le configuration del gestor de visualisation era incomplete"

#: src/modules/dracut/main.py:29
msgid "Creating initramfs with dracut."
msgstr "Creation de initramfs con dracut."

#: src/modules/dracut/main.py:63
msgid "Failed to run dracut"
msgstr "Falleva a executar dracut"

#: src/modules/dracut/main.py:64
#, python-brace-format
msgid "Dracut failed to run on the target with return code: {return_code}"
msgstr ""
"Dracut falleva a executar sur le scopo con le codice de retorno: "
"{return_code}"

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "Labor ficticie de python."

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:104
#: src/modules/dummypython/main.py:105
msgid "Dummy python step {}"
msgstr "Passo ficticie de python {}"

#: src/modules/fstab/main.py:29
msgid "Writing fstab."
msgstr "Scriptura de fstab."

#: src/modules/fstab/main.py:382 src/modules/fstab/main.py:388
#: src/modules/fstab/main.py:416 src/modules/initcpiocfg/main.py:267
#: src/modules/initcpiocfg/main.py:271 src/modules/initramfscfg/main.py:85
#: src/modules/initramfscfg/main.py:89 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:344 src/modules/networkcfg/main.py:106
#: src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/rawfs/main.py:165
msgid "Configuration Error"
msgstr "Error de configuration"

#: src/modules/fstab/main.py:383 src/modules/initramfscfg/main.py:86
#: src/modules/mount/main.py:345 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/rawfs/main.py:166
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "Necun partition es definite pro esser usate per <pre>{!s}</pre>."

#: src/modules/fstab/main.py:389 src/modules/initramfscfg/main.py:90
#: src/modules/localecfg/main.py:141 src/modules/networkcfg/main.py:107
#: src/modules/openrcdmcryptcfg/main.py:77
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr ""
"Necun puncto de montage de radice es date pro esser usate per "
"<pre>{!s}</pre>."

#: src/modules/fstab/main.py:417
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr ""
"Necun configuration <pre>{!s}</pre> es date pro esser usate per "
"<pre>{!s}</pre>."

#: src/modules/grubcfg/main.py:30
msgid "Configure GRUB."
msgstr "Configurar GRUB."

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "Configuration de horologio de hardware."

#: src/modules/initcpiocfg/main.py:27
msgid "Configuring mkinitcpio."
msgstr " Configuration de mkinitcpio."

#: src/modules/initcpiocfg/main.py:268
msgid "No partitions are defined for <pre>initcpiocfg</pre>."
msgstr "Necun partition es definite pro <pre>initcpiocfg</pre>."

#: src/modules/initcpiocfg/main.py:272
msgid "No root mount point for <pre>initcpiocfg</pre>."
msgstr "Necun partition es definite pro <pre>initcpiocfg</pre>."

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr " Configuration de initramfs."

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "Configuration de parametros regional."

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr "Creation de initramfs con mkinitfs."

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr "Falleva a executar mkinitfs sur le scopo"

#: src/modules/mkinitfs/main.py:50
msgid "The exit code was {}"
msgstr "Le codice de exito era {}"

#: src/modules/mount/main.py:43
msgid "Mounting partitions."
msgstr "Montage de partitiones."

#: src/modules/mount/main.py:171 src/modules/mount/main.py:207
msgid "Internal error mounting zfs datasets"
msgstr "Error interne durante le montage de collection de datos de zfs"

#: src/modules/mount/main.py:183
msgid "Failed to import zpool"
msgstr "Falleva a importar zpool"

#: src/modules/mount/main.py:199
msgid "Failed to unlock zpool"
msgstr "Falleva a disblocar zpool"

#: src/modules/mount/main.py:216 src/modules/mount/main.py:221
msgid "Failed to set zfs mountpoint"
msgstr "Falleva a definir le puncto de montage de zfs"

#: src/modules/mount/main.py:386
msgid "zfs mounting error"
msgstr "Error de montage de zfs"

#: src/modules/networkcfg/main.py:30
msgid "Saving network configuration."
msgstr "Salveguarda de configuration de rete."

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "Configuration de servicio OpenRC dmcrypt."

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "Installar pacchettos."

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "Processamento de pacchettos (%(count)d / %(total)d)"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "Installante un pacchetto."
msgstr[1] "Installation de %(num)d pacchettos."

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "Removente un pacchetto."
msgstr[1] "Remotion de %(num)d pacchettos."

#: src/modules/packages/main.py:775 src/modules/packages/main.py:787
#: src/modules/packages/main.py:815
msgid "Package Manager error"
msgstr "Error del gestor de pacchettos"

#: src/modules/packages/main.py:776
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr ""
"Le gestor de pacchettos non poteva preparar le actualisationes. Le commando "
"<pre>{!s}</pre> retornava le codice de error {!s}."

#: src/modules/packages/main.py:788
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr ""
"Le gestor de pacchettos non poteva actualisar le systema. Le commando "
"<pre>{!s}</pre> retornava le codice de error {!s}."

#: src/modules/packages/main.py:816
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Le gestor de pacchettos non poteva facer le modificationes al systema "
"installate. Le commando <pre>{!s}</pre> retornava le codice de error {!s}."

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "Configurar thema Plymouth"

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "Installation de datos."

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "Configurar servicios OpenRC"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr ""
"Non pote adder le servicio {name!s} al nivello de execution {level!s}."

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr ""
"Non pote remover le servicio {name!s} del nivello de execution {level!s}."

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""
"Servicio de action <code>{arg!s}</code> discognoscite pro le servicio "
"{name!s} in le nivello de execution {level!s}."

#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "Non pote modificar le servicio"

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
"Le appello <code>rc-update {arg!s}</code> in “chroot” retornava le codice de"
" error {num!s}."

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "Le nivello de execution del scopo non existe"

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"Le percurso pro le nivello de execution {level!s} es <code>{path!s}</code>, "
"que no existe."

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "Le servicio de scopo non existe"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"Le percurso pro le servicio {name!s} es <code>{path!s}</code>, que no "
"existe."

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd units"
msgstr "Configurar unitates systemd"

#: src/modules/services-systemd/main.py:64
msgid "Cannot modify unit"
msgstr "Non pote modificar le unitate"

#: src/modules/services-systemd/main.py:65
msgid ""
"<code>systemctl {_action!s}</code> call in chroot returned error code "
"{_exit_code!s}."
msgstr ""
"Le appello <code>systemctl {_action!s}</code> in “chroot” retornava le "
"codice de error {_exit_code!s}."

#: src/modules/services-systemd/main.py:66
msgid "Cannot {_action!s} systemd unit <code>{_name!s}</code>."
msgstr "Non pote {_action!s} le unitate systemd <code>{_name!s}</code>."

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "Reimplente le systemas de files. "

#: src/modules/unpackfs/main.py:255
msgid "rsync failed with error code {}."
msgstr "rsync falleva con le codice de error {}."

#: src/modules/unpackfs/main.py:300
msgid "Unpacking image {}/{}, file {}/{}"
msgstr "Dispacchettante le imagine {}/{}, file {}/{}"

#: src/modules/unpackfs/main.py:315
msgid "Starting to unpack {}"
msgstr "Initiante a dispacchettar {}"

#: src/modules/unpackfs/main.py:324 src/modules/unpackfs/main.py:480
msgid "Failed to unpack image \"{}\""
msgstr "Falleva a dispacchettar le imagina «{}»"

#: src/modules/unpackfs/main.py:443
msgid "No mount point for root partition"
msgstr "Necun puncto de montage pro le partition radice"

#: src/modules/unpackfs/main.py:444
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr "globalstorage non contine un clave rootMountPoint."

#: src/modules/unpackfs/main.py:447
msgid "Bad mount point for root partition"
msgstr "Le puncto de montage pro le partition radice incorrecte"

#: src/modules/unpackfs/main.py:448
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr "rootMountPoint es “{}”, que no existe."

#: src/modules/unpackfs/main.py:452 src/modules/unpackfs/main.py:468
#: src/modules/unpackfs/main.py:472 src/modules/unpackfs/main.py:478
#: src/modules/unpackfs/main.py:515
msgid "Bad unpackfs configuration"
msgstr "Configuration de unpackfs incorrecte"

#: src/modules/unpackfs/main.py:453
msgid "There is no configuration information."
msgstr "Il non ha information de configuration."

#: src/modules/unpackfs/main.py:469
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr ""
"Le systema de files para “{}” ({}) non es supportate per tu nucleo actual"

#: src/modules/unpackfs/main.py:473
msgid "The source filesystem \"{}\" does not exist"
msgstr "Le fonte del systema de files “{}” non existe"

#: src/modules/unpackfs/main.py:479
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr ""
"Falleva a trovar unsquashfs, assecura te que tu ha le pacchetto squashfs-"
"tools installate."

#: src/modules/unpackfs/main.py:516
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "Le destination “{}” in le systema de scopo non es un directorio"

#: src/modules/zfshostid/main.py:27
msgid "Copying zfs generated hostid."
msgstr "Copia de hostid generate per zfs."
