# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# Adriaan de Groot <groot@kde.org>, 2018
# Lajos Pasztor <mrlajos@gmail.com>, 2019
# summoner001, 2024
# miku84, 2024
# Balázs Meskó <meskobalazs@mailbox.org>, 2024
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-11-29 13:55+0100\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: Balázs Meskó <meskobalazs@mailbox.org>, 2024\n"
"Language-Team: Hungarian (https://app.transifex.com/calamares/teams/20061/hu/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: hu\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: src/modules/bootloader/main.py:46
msgid "Install bootloader."
msgstr "Rendszerbetöltő telepítése."

#: src/modules/bootloader/main.py:671
msgid "Failed to install grub, no partitions defined in global storage"
msgstr ""
"A grub telepítése sikertelen, a globális tárolóban nincsenek partíciók "
"definiálva"

#: src/modules/bootloader/main.py:931
msgid "Bootloader installation error"
msgstr "Rendszerbetöltő telepítési hiba"

#: src/modules/bootloader/main.py:932
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr ""
"A rendszerbetöltőt nem sikerült telepíteni. A(z) <pre>{!s}</pre> telepítési "
"parancs ezt hibakódot adta vissza: {!s}."

#: src/modules/displaymanager/main.py:525
msgid "Cannot write LXDM configuration file"
msgstr "Az LXDM konfigurációs fájl nem írható"

#: src/modules/displaymanager/main.py:526
msgid "LXDM config file {!s} does not exist"
msgstr "A(z) {!s} LXDM konfigurációs fájl nem létezik"

#: src/modules/displaymanager/main.py:614
msgid "Cannot write LightDM configuration file"
msgstr "A LightDM konfigurációs fájl nem írható"

#: src/modules/displaymanager/main.py:615
msgid "LightDM config file {!s} does not exist"
msgstr "A(z) {!s} LightDM konfigurációs fájl nem létezik"

#: src/modules/displaymanager/main.py:700
msgid "Cannot configure LightDM"
msgstr "A LightDM nem állítható be"

#: src/modules/displaymanager/main.py:701
msgid "No LightDM greeter installed."
msgstr "Nincs LightDM üdvözlő telepítve."

#: src/modules/displaymanager/main.py:732
msgid "Cannot write SLIM configuration file"
msgstr "A SLIM konfigurációs fájl nem írható"

#: src/modules/displaymanager/main.py:733
msgid "SLIM config file {!s} does not exist"
msgstr "A(z) {!s} SLIM konfigurációs fájl nem létezik"

#: src/modules/displaymanager/main.py:956
msgid "No display managers selected for the displaymanager module."
msgstr "Nincs kijelzőkezelő kiválasztva a kijelzőkezelő modulhoz."

#: src/modules/displaymanager/main.py:957
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr ""
"A displaymanagers lista üres vagy nincs meghatározva a globalstorage vagy a "
"displaymanager.conf fájl egyikében."

#: src/modules/displaymanager/main.py:1044
msgid "Display manager configuration was incomplete"
msgstr "A kijelzőkezelő konfigurációja hiányos volt"

#: src/modules/dracut/main.py:29
msgid "Creating initramfs with dracut."
msgstr "Az initramfs létrehozása a dracuttal."

#: src/modules/dracut/main.py:63
msgid "Failed to run dracut"
msgstr "A dracut futtatása nem sikerült"

#: src/modules/dracut/main.py:64
#, python-brace-format
msgid "Dracut failed to run on the target with return code: {return_code}"
msgstr ""
"A dracut futtatása a célon sikertelen, a visszatérési kód: {return_code}"

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "Hamis Python feladat."

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:104
#: src/modules/dummypython/main.py:105
msgid "Dummy python step {}"
msgstr "Hamis {}. Python lépés"

#: src/modules/fstab/main.py:29
msgid "Writing fstab."
msgstr "Az fstab írása."

#: src/modules/fstab/main.py:382 src/modules/fstab/main.py:388
#: src/modules/fstab/main.py:416 src/modules/initcpiocfg/main.py:267
#: src/modules/initcpiocfg/main.py:271 src/modules/initramfscfg/main.py:85
#: src/modules/initramfscfg/main.py:89 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:344 src/modules/networkcfg/main.py:106
#: src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/rawfs/main.py:165
msgid "Configuration Error"
msgstr "Konfigurációs hiba"

#: src/modules/fstab/main.py:383 src/modules/initramfscfg/main.py:86
#: src/modules/mount/main.py:345 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/rawfs/main.py:166
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "Nincsenek partíciók meghatározva a(z) <pre>{!s}</pre> használatához."

#: src/modules/fstab/main.py:389 src/modules/initramfscfg/main.py:90
#: src/modules/localecfg/main.py:141 src/modules/networkcfg/main.py:107
#: src/modules/openrcdmcryptcfg/main.py:77
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr "Nincs root csatolási pont megadva a(z) <pre>{!s}</pre> használatához."

#: src/modules/fstab/main.py:417
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr ""
"Nincs megadva <pre>{!s}</pre> konfiguráció a(z) <pre>{!s}</pre> "
"használatához."

#: src/modules/grubcfg/main.py:30
msgid "Configure GRUB."
msgstr "GRUB konfigurálása."

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "Rendszeridő beállítása."

#: src/modules/initcpiocfg/main.py:27
msgid "Configuring mkinitcpio."
msgstr "Az mkinitcpio konfigurálása."

#: src/modules/initcpiocfg/main.py:268
msgid "No partitions are defined for <pre>initcpiocfg</pre>."
msgstr "Az <pre>initcpiocfg</pre> számára nincsenek partíciók definiálva."

#: src/modules/initcpiocfg/main.py:272
msgid "No root mount point for <pre>initcpiocfg</pre>."
msgstr "Nincs root csatolási pont az <pre>initcpiocfg</pre> számára."

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "Az initramfs konfigurálása."

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "Az területi beállítások konfigurálása."

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr "Initramfs létrehozása az mkinitfs segítségével."

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr "Nem sikerült futtatni az mkinitfs-t a célon"

#: src/modules/mkinitfs/main.py:50
msgid "The exit code was {}"
msgstr "A kilépési kód {} volt."

#: src/modules/mount/main.py:43
msgid "Mounting partitions."
msgstr "Partíciók csatolása."

#: src/modules/mount/main.py:171 src/modules/mount/main.py:207
msgid "Internal error mounting zfs datasets"
msgstr "Belső hiba a zfs adatkészletek csatolásakor"

#: src/modules/mount/main.py:183
msgid "Failed to import zpool"
msgstr "A zpool importálása sikertelen"

#: src/modules/mount/main.py:199
msgid "Failed to unlock zpool"
msgstr "A zpool feloldása nem sikerült"

#: src/modules/mount/main.py:216 src/modules/mount/main.py:221
msgid "Failed to set zfs mountpoint"
msgstr "Nem sikerült beállítani a zfs csatolási pontot"

#: src/modules/mount/main.py:386
msgid "zfs mounting error"
msgstr "zfs csatolási hiba"

#: src/modules/networkcfg/main.py:30
msgid "Saving network configuration."
msgstr "Hálózati konfiguráció mentése."

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "OpenRC dmcrypt szolgáltatás konfigurálása."

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "Csomagok telepítése."

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "Csomagok feldolgozása (%(count)d / %(total)d)"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "Egy csomag telepítése."
msgstr[1] "%(num)d csomag telepítése."

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "Egy csomag eltávolítása."
msgstr[1] "%(num)d csomag eltávolítása."

#: src/modules/packages/main.py:775 src/modules/packages/main.py:787
#: src/modules/packages/main.py:815
msgid "Package Manager error"
msgstr "Csomagkezelő hiba"

#: src/modules/packages/main.py:776
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr ""
"A csomagkezelő nem tudott frissítéseket előkészíteni. A(z) <pre>{!s}</pre> "
"parancs {!s} hibakódot adott vissza."

#: src/modules/packages/main.py:788
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr ""
"A csomagkezelő nem tudta frissíteni a rendszert. A(z) <pre>{!s}</pre> "
"parancs {!s} hibakódot adott vissza."

#: src/modules/packages/main.py:816
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr ""
"A csomagkezelő nem tudott módosítani a telepített rendszeren. A(z) "
"<pre>{!s}</pre> parancs {!s} hibakódot adott vissza."

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "Plymouth téma beállítása"

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "Adatok telepítése."

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "OpenRC szolgáltatások beállítása"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr "Nem lehet  {name!s} szolgáltatást hozzáadni a run-level {level!s}."

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr ""
"Nem lehet törölni a(z) {name!s} szolgáltatást a következő futási szintből: "
"{level!s}."

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""
"Ismeretlen <code>{arg!s}</code> service-action a(z) {name!s} szolgáltatáshoz"
" ezen a futási szinten: {level!s}."

#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "A szolgáltatást nem lehet módosítani"

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
"<code>rc-update {arg!s}</code> hívás a chroot-ban hibakódot adott: {num!s}."

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "A célzott futási szint nem létezik"

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"A futási szint ({level!s}) elérési útja: <code>{path!s}</code>, amely nem "
"létezik."

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "A célszolgáltatás nem létezik"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"A(z) {name!s} szolgáltatás elérési útja: <code>{path!s}</code>, amely nem "
"létezik."

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd units"
msgstr "A systemd összetevők konfigurálása"

#: src/modules/services-systemd/main.py:64
msgid "Cannot modify unit"
msgstr "Az összetevőt nem lehet módosítani"

#: src/modules/services-systemd/main.py:65
msgid ""
"<code>systemctl {_action!s}</code> call in chroot returned error code "
"{_exit_code!s}."
msgstr ""
"A <code>systemctl {_action!s}</code> hívás a chrootban {_exit_code!s} "
"hibakódot adott vissza."

#: src/modules/services-systemd/main.py:66
msgid "Cannot {_action!s} systemd unit <code>{_name!s}</code>."
msgstr ""
"A(z) <code>{_name!s}</code> systemd egységen nem hajtható végre ez a "
"művelet: {_action!s}."

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "Fájlrendszerek betöltése."

#: src/modules/unpackfs/main.py:255
msgid "rsync failed with error code {}."
msgstr "Az rsync sikertelen ezzel a hibakóddal: {}."

#: src/modules/unpackfs/main.py:300
msgid "Unpacking image {}/{}, file {}/{}"
msgstr "{}./{} kép kibontása, {}./{} fájl"

#: src/modules/unpackfs/main.py:315
msgid "Starting to unpack {}"
msgstr "A(z) {} kibontásának megkezdése"

#: src/modules/unpackfs/main.py:324 src/modules/unpackfs/main.py:480
msgid "Failed to unpack image \"{}\""
msgstr "A(z) „{}” kép kibontása sikertelen"

#: src/modules/unpackfs/main.py:443
msgid "No mount point for root partition"
msgstr "Nincs csatolási pont a root partíciónál"

#: src/modules/unpackfs/main.py:444
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr "A globalstorage nem tartalmaz „rootMountPoint” kulcsot."

#: src/modules/unpackfs/main.py:447
msgid "Bad mount point for root partition"
msgstr "Hibás csatolási pont a root partíciónál"

#: src/modules/unpackfs/main.py:448
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr "A rootMountPoint a következő: „{}”, amely nem létezik."

#: src/modules/unpackfs/main.py:452 src/modules/unpackfs/main.py:468
#: src/modules/unpackfs/main.py:472 src/modules/unpackfs/main.py:478
#: src/modules/unpackfs/main.py:515
msgid "Bad unpackfs configuration"
msgstr "Hibás unpackfs konfiguráció"

#: src/modules/unpackfs/main.py:453
msgid "There is no configuration information."
msgstr "Nincsenek konfigurációs információk."

#: src/modules/unpackfs/main.py:469
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr "A jelenlegi kernel nem támogatja a(z) „{}” ({}) fájlrendszerét"

#: src/modules/unpackfs/main.py:473
msgid "The source filesystem \"{}\" does not exist"
msgstr "A(z) „{}” forrásfájlrendszer nem létezik"

#: src/modules/unpackfs/main.py:479
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr ""
"Nem sikerült megtalálni az unsquashfs fájlt, ellenőrizze, hogy telepítve "
"van-e a squashfs-tools csomag."

#: src/modules/unpackfs/main.py:516
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "A(z) „{}” cél a célrendszerben nem egy könyvtár"

#: src/modules/zfshostid/main.py:27
msgid "Copying zfs generated hostid."
msgstr "A zfs által előállított hostid másolása."
