# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# André Marcelo Alvarenga <alvarenga@kde.org>, 2020
# Guilherme, 2023
# DIONARLEY VIEIRA, 2024
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-11-29 13:55+0100\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: DIONARLEY VIEIRA, 2024\n"
"Language-Team: Portuguese (Brazil) (https://app.transifex.com/calamares/teams/20061/pt_BR/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: pt_BR\n"
"Plural-Forms: nplurals=3; plural=(n == 0 || n == 1) ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;\n"

#: src/modules/bootloader/main.py:46
msgid "Install bootloader."
msgstr "Instalar carregador de inicialização."

#: src/modules/bootloader/main.py:671
msgid "Failed to install grub, no partitions defined in global storage"
msgstr ""
"Falha ao instalar o grub, não há partições definidas no armazenamento global"

#: src/modules/bootloader/main.py:931
msgid "Bootloader installation error"
msgstr "Erro de instalação do carregador de inicialização"

#: src/modules/bootloader/main.py:932
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr ""
"O carregador de inicialização não pôde ser instalado. O comando de "
"instalação <pre>{!s}</pre> retornou o código de erro {!s}."

#: src/modules/displaymanager/main.py:525
msgid "Cannot write LXDM configuration file"
msgstr "Não foi possível gravar o arquivo de configuração do LXDM"

#: src/modules/displaymanager/main.py:526
msgid "LXDM config file {!s} does not exist"
msgstr "O arquivo de configuração {!s} do LXDM não existe"

#: src/modules/displaymanager/main.py:614
msgid "Cannot write LightDM configuration file"
msgstr "Não foi possível gravar o arquivo de configuração do LightDM"

#: src/modules/displaymanager/main.py:615
msgid "LightDM config file {!s} does not exist"
msgstr "O arquivo de configuração {!s} do LightDM não existe"

#: src/modules/displaymanager/main.py:700
msgid "Cannot configure LightDM"
msgstr "Não é possível configurar o LightDM"

#: src/modules/displaymanager/main.py:701
msgid "No LightDM greeter installed."
msgstr "Não há nenhuma tela de login do LightDM instalada."

#: src/modules/displaymanager/main.py:732
msgid "Cannot write SLIM configuration file"
msgstr "Não foi possível gravar o arquivo de configuração do SLIM"

#: src/modules/displaymanager/main.py:733
msgid "SLIM config file {!s} does not exist"
msgstr "O arquivo de configuração {!s} do SLIM não existe"

#: src/modules/displaymanager/main.py:956
msgid "No display managers selected for the displaymanager module."
msgstr ""
"Nenhum gerenciador de exibição selecionado para o módulo do displaymanager."

#: src/modules/displaymanager/main.py:957
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr ""
"A lista de displaymanagers está vazia ou indefinida em ambos globalstorage e"
" displaymanager.conf."

#: src/modules/displaymanager/main.py:1044
msgid "Display manager configuration was incomplete"
msgstr "A configuração do gerenciador de exibição está incompleta"

#: src/modules/dracut/main.py:29
msgid "Creating initramfs with dracut."
msgstr "Criando initramfs com dracut."

#: src/modules/dracut/main.py:63
msgid "Failed to run dracut"
msgstr "Falha ao executar dracut"

#: src/modules/dracut/main.py:64
#, python-brace-format
msgid "Dracut failed to run on the target with return code: {return_code}"
msgstr ""
"O Dracut falhou ao ser executado no alvo com código de retorno: "
"{return_code}"

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "Tarefa modelo python."

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:104
#: src/modules/dummypython/main.py:105
msgid "Dummy python step {}"
msgstr "Etapa modelo python {}"

#: src/modules/fstab/main.py:29
msgid "Writing fstab."
msgstr "Escrevendo fstab."

#: src/modules/fstab/main.py:382 src/modules/fstab/main.py:388
#: src/modules/fstab/main.py:416 src/modules/initcpiocfg/main.py:267
#: src/modules/initcpiocfg/main.py:271 src/modules/initramfscfg/main.py:85
#: src/modules/initramfscfg/main.py:89 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:344 src/modules/networkcfg/main.py:106
#: src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/rawfs/main.py:165
msgid "Configuration Error"
msgstr "Erro de Configuração."

#: src/modules/fstab/main.py:383 src/modules/initramfscfg/main.py:86
#: src/modules/mount/main.py:345 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/rawfs/main.py:166
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "Sem partições definidas para uso por <pre>{!s}</pre>."

#: src/modules/fstab/main.py:389 src/modules/initramfscfg/main.py:90
#: src/modules/localecfg/main.py:141 src/modules/networkcfg/main.py:107
#: src/modules/openrcdmcryptcfg/main.py:77
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr ""
"Nenhum ponto de montagem para o root fornecido para uso por <pre>{!s}</pre>."

#: src/modules/fstab/main.py:417
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr ""
"Nenhuma configuração <pre>{!s}</pre> é dada para que <pre>{!s}</pre> possa "
"utilizar."

#: src/modules/grubcfg/main.py:30
msgid "Configure GRUB."
msgstr "Configurar GRUB."

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "Configurando relógio de hardware."

#: src/modules/initcpiocfg/main.py:27
msgid "Configuring mkinitcpio."
msgstr "Configurando mkinitcpio."

#: src/modules/initcpiocfg/main.py:268
msgid "No partitions are defined for <pre>initcpiocfg</pre>."
msgstr "Sem partições definidas para uso pelo <pre>initcpiocfg</pre>."

#: src/modules/initcpiocfg/main.py:272
msgid "No root mount point for <pre>initcpiocfg</pre>."
msgstr "Nenhum ponto de montagem root para o<pre>initcpiocfg</pre>."

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "Configurando initramfs."

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "Configurando locais."

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr "Criando initramfs com mkinitfs."

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr "Falha ao executar mkinitfs no alvo"

#: src/modules/mkinitfs/main.py:50
msgid "The exit code was {}"
msgstr "O código de saída foi {}"

#: src/modules/mount/main.py:43
msgid "Mounting partitions."
msgstr "Montando partições."

#: src/modules/mount/main.py:171 src/modules/mount/main.py:207
msgid "Internal error mounting zfs datasets"
msgstr "Erro interno ao montar datasets zfs"

#: src/modules/mount/main.py:183
msgid "Failed to import zpool"
msgstr "Falha ao importar zpool"

#: src/modules/mount/main.py:199
msgid "Failed to unlock zpool"
msgstr "Falha ao desbloquear zpool"

#: src/modules/mount/main.py:216 src/modules/mount/main.py:221
msgid "Failed to set zfs mountpoint"
msgstr "Falha ao definir o ponto de montagem zfs"

#: src/modules/mount/main.py:386
msgid "zfs mounting error"
msgstr "erro de montagem zfs"

#: src/modules/networkcfg/main.py:30
msgid "Saving network configuration."
msgstr "Salvando configuração de rede."

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "Configurando serviço dmcrypt do OpenRC."

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "Instalar pacotes."

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "Processando pacotes (%(count)d / %(total)d)"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "Instalando um pacote."
msgstr[1] "Instalando %(num)d pacotes."
msgstr[2] "Instalando %(num)d pacotes."

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "Removendo um pacote."
msgstr[1] "Removendo %(num)d pacotes."
msgstr[2] "Removendo %(num)d pacotes."

#: src/modules/packages/main.py:775 src/modules/packages/main.py:787
#: src/modules/packages/main.py:815
msgid "Package Manager error"
msgstr "Erro do Gerenciador de Pacotes"

#: src/modules/packages/main.py:776
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr ""
"O gerenciador de pacotes não pôde preparar as atualizações. O comando "
"<pre>{!s}</pre> retornou o código de erro {!s}."

#: src/modules/packages/main.py:788
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr ""
"O gerenciador de pacotes não pôde atualizar o sistema. O comando "
"<pre>{!s}</pre> retornou o código de erro {!s}."

#: src/modules/packages/main.py:816
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr ""
"O gerenciador de pacotes não pôde fazer mudanças no sistema instalado. O "
"comando <pre>{!s}</pre> retornou o código de erro {!s}."

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "Configurar tema do Plymouth"

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "Instalando os dados."

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "Configurar serviços do OpenRC"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr ""
"Não é possível adicionar serviço {name!s} ao nível de execução {level!s}."

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr ""
"Não é possível remover serviço {name!s} do nível de execução {level!s}."

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""
"Serviço de ação <code>{arg!s}</code> desconhecido para o serviço {name!s} no"
" nível de execução {level!s}."

#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "Não é possível modificar o serviço"

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
"Chamada <code>rc-update {arg!s}</code> no chroot retornou o código de erro "
"{num!s}."

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "O nível de execução de destino não existe"

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"O caminho para o nível de execução {level!s} é <code>{path!s}</code>, que "
"não existe."

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "O serviço de destino não existe"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"O caminho para o serviço {name!s} é <code>{path!s}</code>, que não existe."

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd units"
msgstr "Configurar unidades systemd"

#: src/modules/services-systemd/main.py:64
msgid "Cannot modify unit"
msgstr "Não foi possível modificar a unidade"

#: src/modules/services-systemd/main.py:65
msgid ""
"<code>systemctl {_action!s}</code> call in chroot returned error code "
"{_exit_code!s}."
msgstr ""
"A chamada <code>systemctl {_action!s}</code> no chroot retornou o código de "
"erro {_exit_code!s}."

#: src/modules/services-systemd/main.py:66
msgid "Cannot {_action!s} systemd unit <code>{_name!s}</code>."
msgstr "Cannot {_action!s} systemd unit <code>{_name!s}</code>."

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "Preenchendo sistemas de arquivos."

#: src/modules/unpackfs/main.py:255
msgid "rsync failed with error code {}."
msgstr "O rsync falhou com o código de erro {}."

#: src/modules/unpackfs/main.py:300
msgid "Unpacking image {}/{}, file {}/{}"
msgstr "Descompactando imagem {}/{}, arquivo {}/{}"

#: src/modules/unpackfs/main.py:315
msgid "Starting to unpack {}"
msgstr "Começando a descompactar {}"

#: src/modules/unpackfs/main.py:324 src/modules/unpackfs/main.py:480
msgid "Failed to unpack image \"{}\""
msgstr "Ocorreu uma falha ao descompactar a imagem \"{}\""

#: src/modules/unpackfs/main.py:443
msgid "No mount point for root partition"
msgstr "Nenhum ponto de montagem para a partição root"

#: src/modules/unpackfs/main.py:444
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr "globalstorage não contém uma chave \"rootMountPoint\"."

#: src/modules/unpackfs/main.py:447
msgid "Bad mount point for root partition"
msgstr "Ponto de montagem incorreto para a partição root"

#: src/modules/unpackfs/main.py:448
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr "rootMountPoint é \"{}\", que não existe."

#: src/modules/unpackfs/main.py:452 src/modules/unpackfs/main.py:468
#: src/modules/unpackfs/main.py:472 src/modules/unpackfs/main.py:478
#: src/modules/unpackfs/main.py:515
msgid "Bad unpackfs configuration"
msgstr "Configuração incorreta do unpackfs"

#: src/modules/unpackfs/main.py:453
msgid "There is no configuration information."
msgstr "Não há informação de configuração."

#: src/modules/unpackfs/main.py:469
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr "Não há suporte para o sistema de arquivos \"{}\" ({}) no seu kernel atual"

#: src/modules/unpackfs/main.py:473
msgid "The source filesystem \"{}\" does not exist"
msgstr "O sistema de arquivos de origem \"{}\" não existe"

#: src/modules/unpackfs/main.py:479
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr ""
"Não foi possível encontrar o unsquashfs, certifique-se de que o pacote "
"squashfs-tools foi instalado."

#: src/modules/unpackfs/main.py:516
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "A destinação \"{}\" no sistema de destino não é um diretório"

#: src/modules/zfshostid/main.py:27
msgid "Copying zfs generated hostid."
msgstr "Copiando hostid gerado pelo zfs."
